### ISSUE TITLE
Unexpected crash with "maximum call stack size exceeded" error

### ISSUE THREAD

**Issue by ceoworks** [vicanso/async-local-storage#12]
The problem occurs locally, but I'm worried about possibility of reproducing this on production servers
version `1.2.0`
```
(node:65032) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
    at get (/Users/mac/project/node_modules/async-local-storage/index.js:21:13)
    at get (/Users/mac/project/node_modules/async-local-storage/index.js:28:12)
    at get (/Users/mac/project/node_modules/async-local-storage/index.js:28:12)
    at get (/Users/mac/project/node_modules/async-local-storage/index.js:28:12)
    at get (/Users/mac/project/node_modules/async-local-storage/index.js:28:12)
    at get (/Users/mac/project/node_modules/async-local-storage/index.js:28:12)
    at get (/Users/mac/project/node_modules/async-local-storage/index.js:28:12)
    at get (/Users/mac/project/node_modules/async-local-storage/index.js:28:12)
    at get (/Users/mac/project/node_modules/async-local-storage/index.js:28:12)
    at get (/Users/mac/project/node_modules/async-local-storage/index.js:28:12)
    at get (/Users/mac/project/node_modules/async-local-storage/index.js:28:12)
    at get (/Users/mac/project/node_modules/async-local-storage/index.js:28:12)
    at get (/Users/mac/project/node_modules/async-local-storage/index.js:28:12)
    at get (/Users/mac/project/node_modules/async-local-storage/index.js:28:12)
    at get (/Users/mac/project/node_modules/async-local-storage/index.js:28:12)
    at get (/Users/mac/project/node_modules/async-local-storage/index.js:28:12)
    at get (/Users/mac/project/node_modules/async-local-storage/index.js:28:12)
    at get (/Users/mac/project/node_modules/async-local-storage/index.js:28:12)
    at get (/Users/mac/project/node_modules/async-local-storage/index.js:28:12)
    at get (/Users/mac/project/node_modules/async-local-storage/index.js:28:12)
    at get (/Users/mac/project/node_modules/async-local-storage/index.js:28:12)
    at get (/Users/mac/project/node_modules/async-local-storage/index.js:28:12)
(node:65032) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

**Comment by vicanso** [comment]
@ceoworks  I am sorry for late reply. Please show me you code and I will have a try.
